const QUOTES = [
  'Small steps, repeated daily, become lasting change.',
  'Honesty with yourself is the foundation of every reset.',
  'Progress is not linear - showing up still counts.',
  'Your body hears everything your mind says. Speak kindly.',
  'Rest is not a reward for finishing - it is part of the work.',
  'One healthy choice today is a vote for the person you are becoming.',
  'You do not have to be perfect to be making progress.',
  'Consistency beats intensity when you are building a life.',
  'Drink the water. Take the walk. Log the truth.',
  'Healing happens in the quiet moments between effort.',
  'What you track, you tend to improve.',
  'Today is a good day to begin again - without guilt.',
  'Strength grows in the reps you did not feel like doing.',
  'Nourish yourself the way you would someone you love.',
  'Your future self is grateful for what you do today.',
  'Breathe. Reset. Continue.',
  'Wellness is a practice, not a destination.',
  'Every log entry is proof that you care about your health.',
  'Let go of yesterday. Lead with intention today.',
  'Movement is medicine for body and mind.',
  'Sleep is not lazy - it is essential recovery.',
  'You are allowed to take up space and take care of yourself.',
  'Honest data leads to honest growth.',
  'Celebrate the wins that only you can see.',
  'A reset is not starting over - it is starting wiser.',
  'Fuel your body. Clear your mind. Trust the process.',
  'Gentle discipline creates freedom.',
  'Your pace is valid. Your path is yours.',
  'Notice what makes you feel alive - do more of that.',
  'Stress less about the number; care more about the trend.',
  'Kindness to yourself is not optional.',
  'The best project you will ever work on is you.',
  'Show up as you are. Improve as you go.',
  'Health is built in ordinary moments, not grand gestures.',
  'Pause before you react. Reset before you continue.',
  'You are one choice away from a better feeling.',
  'Let today be evidence of your commitment.',
  'Comparison steals joy - track your own story.',
  'Eat with intention. Move with purpose. Rest without apology.',
  'Courage looks like logging the hard days too.',
  'Your habits are teaching your body what to expect.',
  'Trust the slow work. It is still working.',
  'A walk outside can reset more than a screen ever will.',
  'Hydration is the simplest act of self-respect.',
  'You deserve the same patience you give others.',
  'Reset the narrative: you are capable of change.',
  'Morning light, steady steps, honest notes.',
  'What feels small today becomes significant over time.',
  'Listen to your body - it speaks in signals, not words.',
  'Gratitude and growth can share the same breath.',
  'Do not wait for motivation. Build momentum.',
  'Your log is a mirror, not a judge.',
  'Plant the habit. Water it daily. Watch it grow.',
  'Be proud of showing up - especially on the messy days.',
  'Honest resets begin with honest numbers.',
  'You are writing a healthier chapter, one day at a time.',
  'Peace is a practice you can choose this morning.',
  'Let effort and ease coexist in your routine.',
  'The goal is sustainable, not spectacular.',
  "Today's effort is tomorrow's baseline.",
  'Reset your expectations, not your worth.',
  'Wellness fits real life - imperfect and beautiful.',
]

export function getDailyQuote(): string {
  const now = new Date()
  const start = new Date(now.getFullYear(), 0, 0)
  const dayOfYear = Math.floor((now.getTime() - start.getTime()) / 86_400_000)
  return QUOTES[dayOfYear % QUOTES.length]
}
